### ISSUE TITLE
Integrate Themes

### ISSUE THREAD

**Issue by VirtDev337** [VirtDev337/JTCAlum#5]
Modify CSS files to include a light and dark theme option.

Possible alternative would be allow user to create custom themes...?

**Comment by kepstein** [comment]
Maybe be careful with "user custom" themes. Maybe allow some customization within a certain range. A good example of this going wrong is the early days of myspace.com. People could customize in anyway they liked - it became a huge mess.

**Comment by VirtDev337** [comment]
The point is to offer a light and dark version,  like so many other sites,  using the Columbia University colors, in order to adhere to common practices.
